import numpy as np
from scipy.stats import norm

class BehavioralAgents:
    """
    Implements a Heterogeneous Agent Model to calculate explicit implied volatility 
    distortions driven by purely behavioral demand.
    
    It models two major distinct agent classes in the Indian Market:
    1. Retail Lottery Buyers: Generate massive demand for deep OTM calls/puts, inflating the wings.
    2. Institutional Hedgers: Generate structural demand for OTM puts (portfolio protection), driving left-skew.
    """
    
    def __init__(self, retail_volume_pct=0.35, inst_volume_pct=0.50):
        self.retail_volume_pct = retail_volume_pct
        self.inst_volume_pct = inst_volume_pct

    def retail_lottery_wing_inflation(self, spot, strike, T, base_iv):
        """
        Retail traders actively bid up options with Deltas < 0.20 due to lottery preference 
        (Cumulative Prospect Theory probability weighting).
        This inflates the wings of the IV smile beyond BS/Heston bounds.
        """
        moneyness = np.log(strike / spot)
        
        # Calculate rough delta
        d1 = (moneyness + (0.5 * base_iv**2) * T) / (base_iv * np.sqrt(T))
        call_delta = norm.cdf(d1)
        put_delta = call_delta - 1.0
        
        inflation_modifier = 0.0
        
        # Call Wing Inflation (Retail chasing OTM calls)
        if strike > spot and call_delta < 0.25:
            # The smaller the delta, the higher the lottery inflation
            lottery_factor = (0.25 - call_delta) / 0.25
            inflation_modifier = 0.02 * lottery_factor * (self.retail_volume_pct / 0.35)
            
        # Put Wing Inflation (Retail chasing cheap OTM puts on expiry days)
        elif strike < spot and abs(put_delta) < 0.25:
            lottery_factor = (0.25 - abs(put_delta)) / 0.25
            inflation_modifier = 0.015 * lottery_factor * (self.retail_volume_pct / 0.35)
            
        return base_iv + inflation_modifier

    def institutional_hedging_skew(self, spot, strike, T, base_iv, fii_net_flow_cr=0):
        """
        Calculates the structural left-skew pressure generated by FII/DII portfolio hedging.
        Institutional limits mandate downside protection, elevating OTM put IV.
        """
        moneyness = np.log(strike / spot)
        skew_modifier = 0.0
        
        # Only applies to OTM puts
        if strike < spot:
            # Deeper the put, stronger the hedge premium demand
            depth = abs(moneyness)
            
            # If FIIs are selling cash, put demand mathematically spikes
            flow_urgency_multiplier = 1.0
            if fii_net_flow_cr < -1000:
                flow_urgency_multiplier = 1.5
            elif fii_net_flow_cr > 1000:
                flow_urgency_multiplier = 0.8
                
            base_skew_premium = 0.03 * min(depth / 0.10, 1.0) # Cap at 10% OTM
            skew_modifier = base_skew_premium * flow_urgency_multiplier * (self.inst_volume_pct / 0.50)
            
        return base_iv + skew_modifier

    def apply_behavioral_distortions(self, spot, strike, T, base_iv, fii_net_flow_cr=0):
        """
        Master function to apply both retail and institutional behavioral distortions to a base IV.
        """
        iv_after_inst = self.institutional_hedging_skew(spot, strike, T, base_iv, fii_net_flow_cr)
        final_distorted_iv = self.retail_lottery_wing_inflation(spot, strike, T, iv_after_inst)
        
        return final_distorted_iv
